@startuml
'https://plantuml.com/class-diagram

package app {

    class App

    package templates {

        class index< <U+002F> >

        class board

        class examples < <U+002F>examples>

        class historyAndRules < <U+002F>history>

        class Game < <U+002F>game>

        App --> index
        App --> examples
        App --> historyAndRules
        App --> Game
        Game --> board
    }

    note top of templates: templates are html.j2 files

    package src {

        class Game {
            + int playTurn(int playerAction)
        }

        class Algorithms {
        }

        package datastructure {

            package tree {

                class Tree {
                    Node[] leafs
                    Node root
                    + void expend()
                    + int is_winning()
                    + void select_next_root(String state)
                }

                class Node {
                    boolean is_max
                    boolean is_leaf
                    boolean is_ending
                    float e
                    Node[] successors
                    Node pred
                    String state
                }

                Tree *--> "1..1 root" Node
            }

            class TreeManager {
                + expend_from_node(Node node,int depth,Tree tree)
                + generate_tree(int depth)
                + generate_next_node_state_list(String list, Char player_char)
                + is_winning(state)
            }

            class HexConstants {
                int[] MAX_START
                int[] MAX_STOP
                int[] MIN_START
                int[] MIN_STOP
                int[] CASES
                int CASES_NB
                char NODE_STATE_MAX
                char NODE_STATE_MIN
                char NODE_STATE_EMPTY
                + get_neighbours(int case)
            }

            TreeManager ..> Tree

        }

        Game ..> TreeManager
        Game --> Algorithms
        Game --> "1..1 state" GameState
        Game *--> "1..1 tree" Tree
        Game --> "1..1 difficulty" Difficulty

        enum GameState {
            UNFINISHED
            MAX_WINNER
            MIN_WINNER
        }

        enum Difficulty {
            EASY
            MEDIUM
            HARD
        }

    }

    App --> src.Game

}

@enduml